package com.usaparel.vpmodel.VO;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Nov 25 09:44:26 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VOChallanSummaryPOLinesRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        SumQty,
        Invalid,
        PoLineId,
        PoHeaderId,
        DeliveryChallanId,
        LineNum,
        ItemDescription,
        VOInvalidChallanQty;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SUMQTY = AttributesEnum.SumQty.index();
    public static final int INVALID = AttributesEnum.Invalid.index();
    public static final int POLINEID = AttributesEnum.PoLineId.index();
    public static final int POHEADERID = AttributesEnum.PoHeaderId.index();
    public static final int DELIVERYCHALLANID = AttributesEnum.DeliveryChallanId.index();
    public static final int LINENUM = AttributesEnum.LineNum.index();
    public static final int ITEMDESCRIPTION = AttributesEnum.ItemDescription.index();
    public static final int VOINVALIDCHALLANQTY = AttributesEnum.VOInvalidChallanQty.index();

    /**
     * This is the default constructor (do not remove).
     */
    public VOChallanSummaryPOLinesRowImpl() {
    }
}

