package com.usaparel.vpmodel.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Nov 25 09:44:26 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VOChallanSummaryPOLinesImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public VOChallanSummaryPOLinesImpl() {
    }
}

