package com.usaparel.vpmodel.VO;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 28 16:34:16 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VOInvalidChallanQtyRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ReShipChallan,
        ChallanId,
        PoHeaderId,
        PackingId,
        PoLineId,
        ChallanNumber,
        Segment1,
        LineNum,
        PackingQty,
        BadQty,
        ShortQty,
        MissingQty,
        ItemId,
        ItemDescription,
        UnitMeasLookupCode,
        ReturnType,
        TotalChallanQty;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int RESHIPCHALLAN = AttributesEnum.ReShipChallan.index();
    public static final int CHALLANID = AttributesEnum.ChallanId.index();
    public static final int POHEADERID = AttributesEnum.PoHeaderId.index();
    public static final int PACKINGID = AttributesEnum.PackingId.index();
    public static final int POLINEID = AttributesEnum.PoLineId.index();
    public static final int CHALLANNUMBER = AttributesEnum.ChallanNumber.index();
    public static final int SEGMENT1 = AttributesEnum.Segment1.index();
    public static final int LINENUM = AttributesEnum.LineNum.index();
    public static final int PACKINGQTY = AttributesEnum.PackingQty.index();
    public static final int BADQTY = AttributesEnum.BadQty.index();
    public static final int SHORTQTY = AttributesEnum.ShortQty.index();
    public static final int MISSINGQTY = AttributesEnum.MissingQty.index();
    public static final int ITEMID = AttributesEnum.ItemId.index();
    public static final int ITEMDESCRIPTION = AttributesEnum.ItemDescription.index();
    public static final int UNITMEASLOOKUPCODE = AttributesEnum.UnitMeasLookupCode.index();
    public static final int RETURNTYPE = AttributesEnum.ReturnType.index();
    public static final int TOTALCHALLANQTY = AttributesEnum.TotalChallanQty.index();

    /**
     * This is the default constructor (do not remove).
     */
    public VOInvalidChallanQtyRowImpl() {
    }
}

