package com.usaparel.vpmodel.VO;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 28 16:34:16 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VOInvalidChallanQtyImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public VOInvalidChallanQtyImpl() {
    }
}

