package com.usaparel.vpmodel.VO;

import com.usaparel.vpmodel.EO.CustShipmentLinesImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 25 10:49:13 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VOXXCustShipmentLinesRowImpl extends ViewRowImpl {


    public static final int ENTITY_CUSTSHIPMENTLINES = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ShipId,
        ShipLineNum,
        ShipNo,
        PoLineId,
        ShipQty,
        PackingSize,
        PackingDivisor,
        Status,
        ShipDate,
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdateDate,
        VersionNumber,
        totalPackingQty,
        VOXXCustShipmentPacking,
        AppModule_LOVStatus1_1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SHIPID = AttributesEnum.ShipId.index();
    public static final int SHIPLINENUM = AttributesEnum.ShipLineNum.index();
    public static final int SHIPNO = AttributesEnum.ShipNo.index();
    public static final int POLINEID = AttributesEnum.PoLineId.index();
    public static final int SHIPQTY = AttributesEnum.ShipQty.index();
    public static final int PACKINGSIZE = AttributesEnum.PackingSize.index();
    public static final int PACKINGDIVISOR = AttributesEnum.PackingDivisor.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int SHIPDATE = AttributesEnum.ShipDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int VERSIONNUMBER = AttributesEnum.VersionNumber.index();
    public static final int TOTALPACKINGQTY = AttributesEnum.totalPackingQty.index();
    public static final int VOXXCUSTSHIPMENTPACKING = AttributesEnum.VOXXCustShipmentPacking.index();
    public static final int APPMODULE_LOVSTATUS1_1 = AttributesEnum.AppModule_LOVStatus1_1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public VOXXCustShipmentLinesRowImpl() {
    }

    /**
     * Gets CustShipmentLines entity object.
     * @return the CustShipmentLines
     */
    public CustShipmentLinesImpl getCustShipmentLines() {
        return (CustShipmentLinesImpl) getEntity(ENTITY_CUSTSHIPMENTLINES);
    }

    /**
     * Gets the attribute value for SHIP_ID using the alias name ShipId.
     * @return the SHIP_ID
     */
    public BigDecimal getShipId() {
        return (BigDecimal) getAttributeInternal(SHIPID);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_ID using the alias name ShipId.
     * @param value value to set the SHIP_ID
     */
    public void setShipId(BigDecimal value) {
        setAttributeInternal(SHIPID, value);
    }

    /**
     * Gets the attribute value for SHIP_LINE_NUM using the alias name ShipLineNum.
     * @return the SHIP_LINE_NUM
     */
    public BigDecimal getShipLineNum() {
        return (BigDecimal) getAttributeInternal(SHIPLINENUM);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_LINE_NUM using the alias name ShipLineNum.
     * @param value value to set the SHIP_LINE_NUM
     */
    public void setShipLineNum(BigDecimal value) {
        setAttributeInternal(SHIPLINENUM, value);
    }

    /**
     * Gets the attribute value for SHIP_NO using the alias name ShipNo.
     * @return the SHIP_NO
     */
    public String getShipNo() {
        return (String) getAttributeInternal(SHIPNO);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_NO using the alias name ShipNo.
     * @param value value to set the SHIP_NO
     */
    public void setShipNo(String value) {
        setAttributeInternal(SHIPNO, value);
    }

    /**
     * Gets the attribute value for PO_LINE_ID using the alias name PoLineId.
     * @return the PO_LINE_ID
     */
    public BigDecimal getPoLineId() {
        return (BigDecimal) getAttributeInternal(POLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for PO_LINE_ID using the alias name PoLineId.
     * @param value value to set the PO_LINE_ID
     */
    public void setPoLineId(BigDecimal value) {
        setAttributeInternal(POLINEID, value);
    }

    /**
     * Gets the attribute value for SHIP_QTY using the alias name ShipQty.
     * @return the SHIP_QTY
     */
    public BigDecimal getShipQty() {
        return (BigDecimal) getAttributeInternal(SHIPQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_QTY using the alias name ShipQty.
     * @param value value to set the SHIP_QTY
     */
    public void setShipQty(BigDecimal value) {
        setAttributeInternal(SHIPQTY, value);
    }

    /**
     * Gets the attribute value for PACKING_SIZE using the alias name PackingSize.
     * @return the PACKING_SIZE
     */
    public BigDecimal getPackingSize() {
        return (BigDecimal) getAttributeInternal(PACKINGSIZE);
    }

    /**
     * Sets <code>value</code> as attribute value for PACKING_SIZE using the alias name PackingSize.
     * @param value value to set the PACKING_SIZE
     */
    public void setPackingSize(BigDecimal value) {
        setAttributeInternal(PACKINGSIZE, value);
    }

    /**
     * Gets the attribute value for PACKING_DIVISOR using the alias name PackingDivisor.
     * @return the PACKING_DIVISOR
     */
    public BigDecimal getPackingDivisor() {
        return (BigDecimal) getAttributeInternal(PACKINGDIVISOR);
    }

    /**
     * Sets <code>value</code> as attribute value for PACKING_DIVISOR using the alias name PackingDivisor.
     * @param value value to set the PACKING_DIVISOR
     */
    public void setPackingDivisor(BigDecimal value) {
        setAttributeInternal(PACKINGDIVISOR, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for SHIP_DATE using the alias name ShipDate.
     * @return the SHIP_DATE
     */
    public Timestamp getShipDate() {
        return (Timestamp) getAttributeInternal(SHIPDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_DATE using the alias name ShipDate.
     * @param value value to set the SHIP_DATE
     */
    public void setShipDate(Timestamp value) {
        setAttributeInternal(SHIPDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public BigDecimal getCreatedBy() {
        return (BigDecimal) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(BigDecimal value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public BigDecimal getLastUpdatedBy() {
        return (BigDecimal) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(BigDecimal value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute totalPackingQty.
     * @return the totalPackingQty
     */
    public BigDecimal gettotalPackingQty() {
        return (BigDecimal) getAttributeInternal(TOTALPACKINGQTY);
    }


    /**
     * Gets the attribute value for VERSION_NUMBER using the alias name VersionNumber.
     * @return the VERSION_NUMBER
     */
    public BigDecimal getVersionNumber() {
        return (BigDecimal) getAttributeInternal(VERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION_NUMBER using the alias name VersionNumber.
     * @param value value to set the VERSION_NUMBER
     */
    public void setVersionNumber(BigDecimal value) {
        setAttributeInternal(VERSIONNUMBER, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link VOXXCustShipmentPacking.
     */
    public RowIterator getVOXXCustShipmentPacking() {
        return (RowIterator) getAttributeInternal(VOXXCUSTSHIPMENTPACKING);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AppModule_LOVStatus1_1.
     */
    public RowSet getAppModule_LOVStatus1_1() {
        return (RowSet) getAttributeInternal(APPMODULE_LOVSTATUS1_1);
    }
}

