package com.usaparel.vpmodel.AM.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 21 13:50:34 PKT 2017
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    int login(String username, String password);

    void sendNotification(String vendor, int pono, int shipQty, int totalPacks);
}

