package com.usaparel.vpmodel.EO;



import java.math.BigDecimal;

import java.sql.Timestamp;


import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 24 12:30:52 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustShipmentLinesImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ShipId,
        ShipLineNum,
        ShipNo,
        PoLineId,
        ShipQty,
        PackingSize,
        PackingDivisor,
        Status,
        ShipDate,
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdateDate,
        VersionNumber;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SHIPID = AttributesEnum.ShipId.index();
    public static final int SHIPLINENUM = AttributesEnum.ShipLineNum.index();
    public static final int SHIPNO = AttributesEnum.ShipNo.index();
    public static final int POLINEID = AttributesEnum.PoLineId.index();
    public static final int SHIPQTY = AttributesEnum.ShipQty.index();
    public static final int PACKINGSIZE = AttributesEnum.PackingSize.index();
    public static final int PACKINGDIVISOR = AttributesEnum.PackingDivisor.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int SHIPDATE = AttributesEnum.ShipDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int VERSIONNUMBER = AttributesEnum.VersionNumber.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CustShipmentLinesImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.usaparel.vpmodel.EO.CustShipmentLines");
    }


    /**
     * Gets the attribute value for ShipId, using the alias name ShipId.
     * @return the value of ShipId
     */
    public BigDecimal getShipId() {
        return (BigDecimal) getAttributeInternal(SHIPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipId.
     * @param value value to set the ShipId
     */
    public void setShipId(BigDecimal value) {
        setAttributeInternal(SHIPID, value);
    }

    /**
     * Gets the attribute value for ShipLineNum, using the alias name ShipLineNum.
     * @return the value of ShipLineNum
     */
    public BigDecimal getShipLineNum() {
        return (BigDecimal) getAttributeInternal(SHIPLINENUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipLineNum.
     * @param value value to set the ShipLineNum
     */
    public void setShipLineNum(BigDecimal value) {
        setAttributeInternal(SHIPLINENUM, value);
    }

    /**
     * Gets the attribute value for ShipNo, using the alias name ShipNo.
     * @return the value of ShipNo
     */
    public String getShipNo() {
        return (String) getAttributeInternal(SHIPNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipNo.
     * @param value value to set the ShipNo
     */
    public void setShipNo(String value) {
        setAttributeInternal(SHIPNO, value);
    }

    /**
     * Gets the attribute value for PoLineId, using the alias name PoLineId.
     * @return the value of PoLineId
     */
    public BigDecimal getPoLineId() {
        return (BigDecimal) getAttributeInternal(POLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PoLineId.
     * @param value value to set the PoLineId
     */
    public void setPoLineId(BigDecimal value) {
        setAttributeInternal(POLINEID, value);
    }

    /**
     * Gets the attribute value for ShipQty, using the alias name ShipQty.
     * @return the value of ShipQty
     */
    public BigDecimal getShipQty() {
        return (BigDecimal) getAttributeInternal(SHIPQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipQty.
     * @param value value to set the ShipQty
     */
    public void setShipQty(BigDecimal value) {
        setAttributeInternal(SHIPQTY, value);
    }

    /**
     * Gets the attribute value for PackingSize, using the alias name PackingSize.
     * @return the value of PackingSize
     */
    public BigDecimal getPackingSize() {
        return (BigDecimal) getAttributeInternal(PACKINGSIZE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PackingSize.
     * @param value value to set the PackingSize
     */
    public void setPackingSize(BigDecimal value) {
        setAttributeInternal(PACKINGSIZE, value);
    }

    /**
     * Gets the attribute value for PackingDivisor, using the alias name PackingDivisor.
     * @return the value of PackingDivisor
     */
    public BigDecimal getPackingDivisor() {
        return (BigDecimal) getAttributeInternal(PACKINGDIVISOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for PackingDivisor.
     * @param value value to set the PackingDivisor
     */
    public void setPackingDivisor(BigDecimal value) {
        setAttributeInternal(PACKINGDIVISOR, value);
    }

    /**
     * Gets the attribute value for Status, using the alias name Status.
     * @return the value of Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Status.
     * @param value value to set the Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for ShipDate, using the alias name ShipDate.
     * @return the value of ShipDate
     */
    public Timestamp getShipDate() {
        return (Timestamp) getAttributeInternal(SHIPDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipDate.
     * @param value value to set the ShipDate
     */
    public void setShipDate(Timestamp value) {
        setAttributeInternal(SHIPDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public BigDecimal getCreatedBy() {
        return (BigDecimal) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(BigDecimal value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public BigDecimal getLastUpdatedBy() {
        return (BigDecimal) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(BigDecimal value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the value of LastUpdateDate
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for VersionNumber, using the alias name VersionNumber.
     * @return the value of VersionNumber
     */
    public BigDecimal getVersionNumber() {
        return (BigDecimal) getAttributeInternal(VERSIONNUMBER);
    }


    /**
     * @param shipId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal shipId) {
        return new Key(new Object[] { shipId });
    }

    @Override
    protected void doDML(int i, TransactionEvent transactionEvent) {
        
        if  (i == this.DML_UPDATE){
            System.out.println("update here...");
            setCreatedBy(BigDecimal.valueOf(Integer.parseInt(ADFContext.getCurrent().getSessionScope().get("userid").toString())));
        }
        super.doDML(i, transactionEvent);
    }
}

