package com.usaparel.vpmodel.EO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 23 09:27:00 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustShipmentDeliveryChallanImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ChallanId,
        ChallanNumber,
        VehicleType,
        DriverContacts,
        ChallanDescription,
        MediumType,
        DeliveryDate,
        ChallanStatus,
        VehicleNumber,
        SupplierId,
        CreatedBy,
        CreationDate,
        UpdatedBy,
        UpdateDate,
        VersionNumber;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CHALLANID = AttributesEnum.ChallanId.index();
    public static final int CHALLANNUMBER = AttributesEnum.ChallanNumber.index();
    public static final int VEHICLETYPE = AttributesEnum.VehicleType.index();
    public static final int DRIVERCONTACTS = AttributesEnum.DriverContacts.index();
    public static final int CHALLANDESCRIPTION = AttributesEnum.ChallanDescription.index();
    public static final int MEDIUMTYPE = AttributesEnum.MediumType.index();
    public static final int DELIVERYDATE = AttributesEnum.DeliveryDate.index();
    public static final int CHALLANSTATUS = AttributesEnum.ChallanStatus.index();
    public static final int VEHICLENUMBER = AttributesEnum.VehicleNumber.index();
    public static final int SUPPLIERID = AttributesEnum.SupplierId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATEDATE = AttributesEnum.UpdateDate.index();
    public static final int VERSIONNUMBER = AttributesEnum.VersionNumber.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CustShipmentDeliveryChallanImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.usaparel.vpmodel.EO.CustShipmentDeliveryChallan");
    }


    /**
     * Gets the attribute value for ChallanId, using the alias name ChallanId.
     * @return the value of ChallanId
     */
    public BigDecimal getChallanId() {
        return (BigDecimal) getAttributeInternal(CHALLANID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ChallanId.
     * @param value value to set the ChallanId
     */
    public void setChallanId(BigDecimal value) {
        setAttributeInternal(CHALLANID, value);
    }

    /**
     * Gets the attribute value for ChallanNumber, using the alias name ChallanNumber.
     * @return the value of ChallanNumber
     */
    public String getChallanNumber() {
        return (String) getAttributeInternal(CHALLANNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for ChallanNumber.
     * @param value value to set the ChallanNumber
     */
    public void setChallanNumber(String value) {
        setAttributeInternal(CHALLANNUMBER, value);
    }

    /**
     * Gets the attribute value for VehicleType, using the alias name VehicleType.
     * @return the value of VehicleType
     */
    public BigDecimal getVehicleType() {
        return (BigDecimal) getAttributeInternal(VEHICLETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for VehicleType.
     * @param value value to set the VehicleType
     */
    public void setVehicleType(BigDecimal value) {
        setAttributeInternal(VEHICLETYPE, value);
    }

    /**
     * Gets the attribute value for DriverContacts, using the alias name DriverContacts.
     * @return the value of DriverContacts
     */
    public String getDriverContacts() {
        return (String) getAttributeInternal(DRIVERCONTACTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for DriverContacts.
     * @param value value to set the DriverContacts
     */
    public void setDriverContacts(String value) {
        setAttributeInternal(DRIVERCONTACTS, value);
    }

    /**
     * Gets the attribute value for ChallanDescription, using the alias name ChallanDescription.
     * @return the value of ChallanDescription
     */
    public String getChallanDescription() {
        return (String) getAttributeInternal(CHALLANDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for ChallanDescription.
     * @param value value to set the ChallanDescription
     */
    public void setChallanDescription(String value) {
        setAttributeInternal(CHALLANDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for MediumType, using the alias name MediumType.
     * @return the value of MediumType
     */
    public BigDecimal getMediumType() {
        return (BigDecimal) getAttributeInternal(MEDIUMTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for MediumType.
     * @param value value to set the MediumType
     */
    public void setMediumType(BigDecimal value) {
        setAttributeInternal(MEDIUMTYPE, value);
    }

    /**
     * Gets the attribute value for DeliveryDate, using the alias name DeliveryDate.
     * @return the value of DeliveryDate
     */
    public Timestamp getDeliveryDate() {
        return (Timestamp) getAttributeInternal(DELIVERYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeliveryDate.
     * @param value value to set the DeliveryDate
     */
    public void setDeliveryDate(Timestamp value) {
        setAttributeInternal(DELIVERYDATE, value);
    }

    /**
     * Gets the attribute value for ChallanStatus, using the alias name ChallanStatus.
     * @return the value of ChallanStatus
     */
    public String getChallanStatus() {
        return (String) getAttributeInternal(CHALLANSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ChallanStatus.
     * @param value value to set the ChallanStatus
     */
    public void setChallanStatus(String value) {
        setAttributeInternal(CHALLANSTATUS, value);
    }

    /**
     * Gets the attribute value for VehicleNumber, using the alias name VehicleNumber.
     * @return the value of VehicleNumber
     */
    public String getVehicleNumber() {
        return (String) getAttributeInternal(VEHICLENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for VehicleNumber.
     * @param value value to set the VehicleNumber
     */
    public void setVehicleNumber(String value) {
        setAttributeInternal(VEHICLENUMBER, value);
    }


    /**
     * Gets the attribute value for SupplierId, using the alias name SupplierId.
     * @return the value of SupplierId
     */
    public BigDecimal getSupplierId() {
        return (BigDecimal) getAttributeInternal(SUPPLIERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SupplierId.
     * @param value value to set the SupplierId
     */
    public void setSupplierId(BigDecimal value) {
        setAttributeInternal(SUPPLIERID, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public BigDecimal getCreatedBy() {
        return (BigDecimal) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(BigDecimal value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public BigDecimal getUpdatedBy() {
        return (BigDecimal) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(BigDecimal value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdateDate, using the alias name UpdateDate.
     * @return the value of UpdateDate
     */
    public Timestamp getUpdateDate() {
        return (Timestamp) getAttributeInternal(UPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdateDate.
     * @param value value to set the UpdateDate
     */
    public void setUpdateDate(Timestamp value) {
        setAttributeInternal(UPDATEDATE, value);
    }

    /**
     * Gets the attribute value for VersionNumber, using the alias name VersionNumber.
     * @return the value of VersionNumber
     */
    public BigDecimal getVersionNumber() {
        return (BigDecimal) getAttributeInternal(VERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for VersionNumber.
     * @param value value to set the VersionNumber
     */
    public void setVersionNumber(BigDecimal value) {
        setAttributeInternal(VERSIONNUMBER, value);
    }

    /**
     * @param challanId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal challanId) {
        return new Key(new Object[] { challanId });
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        
        if (operation == DML_INSERT){
            setChallanStatus("SAVED");
            setSupplierId(new BigDecimal(ADFContext.getCurrent().getSessionScope().get("userid").toString()));
            setCreatedBy(new BigDecimal(ADFContext.getCurrent().getSessionScope().get("userid").toString()));
            setUpdatedBy(new BigDecimal(ADFContext.getCurrent().getSessionScope().get("userid").toString()));
            
            System.out.println("DML_INSERT: CustShipmentDeliveryChallanImpl.java");
        }else if (operation == DML_UPDATE){
            System.out.println(getChallanStatus());
            if (!getChallanStatus().equals("SHIPPED")){
                setChallanStatus("UPDATED");    
            }
            setUpdatedBy(new BigDecimal(ADFContext.getCurrent().getSessionScope().get("userid").toString()));
            System.out.println("DML_UPDATE: CustShipmentDeliveryChallanImpl.java");
        }else if(operation == DML_DELETE){
            System.out.println("DML_DELETE: CustShipmentDeliveryChallanImpl.java");
        }
        super.doDML(operation, e);
    }
}

