package com.usaparel.vpmodel.VO.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 30 11:26:24 PKT 2017
// ---------------------------------------------------------------------
public interface VOCustShipmentDeliveryChallanRow extends Row {
    void shipChallan();
}

